import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { context } from 'esbuild';
import postcss from 'postcss';
import postcssConfig from '../postcss.config.mjs';

export const root = fileURLToPath(new URL('../', import.meta.url));

export function createAssetContext(workingDirectory = root) {
  return context({
    absWorkingDir: workingDirectory,
    entryPoints: {
      'js/syutoi.min': 'src/client/main.ts',
      'css/syutoi.min': 'src/styles/main.css',
      'js/lightbox.min': 'src/client/lightbox.ts',
      'js/photoswipe.min': 'src/client/photoswipe.ts',
      'css/lightbox.min': 'src/styles/lightbox.css',
      'js/search.min': 'src/client/search.ts',
      'css/search.min': 'src/styles/search.css'
    },
    outdir: 'source',
    bundle: true,
    write: false,
    platform: 'browser',
    format: 'iife',
    target: 'es2020',
    minify: true,
    charset: 'utf8',
    legalComments: 'none',
    banner: {
      js: '/* Generated by pnpm build:theme. Edit src/client instead. */',
      css: '/* Generated by pnpm build:theme. Edit src/styles instead. */'
    },
    logLevel: 'info',
    plugins: [{
      name: 'publish-successful-build',
      setup(build) {
        build.onEnd(async result => {
          if (result.errors.length) return;
          for (const file of result.outputFiles) {
            try {
              if ((await readFile(file.path)).equals(Buffer.from(file.contents))) continue;
            } catch (error) {
              if (error.code !== 'ENOENT') throw error;
            }
            await mkdir(dirname(file.path), { recursive: true });
            // Hidden temporary files cannot become routes during Hexo's scan.
            const temporary = join(dirname(file.path), `.${basename(file.path)}.tmp`);
            await writeFile(temporary, file.contents);
            await rename(temporary, file.path);
          }
        });
      }
    }, {
      name: 'postcss',
      setup(build) {
        build.onLoad({ filter: /\.css$/ }, async ({ path }) => {
          const result = await postcss(postcssConfig.plugins).process(await readFile(path, 'utf8'), {
            from: path,
            map: false
          });
          return {
            contents: result.css,
            loader: 'css',
            resolveDir: dirname(path),
            watchFiles: [path, ...result.messages.filter(message => message.type === 'dependency').map(message => message.file)],
            warnings: result.warnings().map(warning => ({ text: warning.toString() }))
          };
        });
      }
    }]
  });
}
